language: generic
sudo: required 
services:
  - docker

before_install:
  - docker build -t masalome/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true masalome/docker-react npm run test 